import {YT, YTNodes} from "youtubei.js";
import {
    channelRelated,
    channelVideo,
    error,
    formatDate,
    formatHtml,
    formatNum,
    obj
} from "../../lib/output";
import type {AuthorStub} from "output";

export default async (path: string[]) => {
    if (path.length < 3) {
        return error("Invalid request, please provide a channel ID");
    }
    try {
        const channel: YT.Channel = await global.client.getChannel(path[2]);
        const about = await channel.getAbout();
        let extras = {
            banners: [],
            subCount: 0,
            totalViews: 0,
            joined: 0,
            autoGenerated: false,
            description: channel.metadata.description,
            descriptionHtml: formatHtml(channel.metadata.description),
            authorVerified: false,
            latestVideos: [],
            channels: []
        };
        // Header info
        if (channel.header.is(YTNodes.C4TabbedHeader)) {
            extras.banners = channel.header.banner;
            extras.subCount = formatNum(channel.header.subscribers.toString());
            extras.authorVerified = channel.header.author.is_verified
        } else if (channel.header.is(YTNodes.PageHeader)) {
            extras.banners = channel.header.content.banner.image;
            extras.subCount = formatNum(channel.header.content.metadata.metadata_rows[1].metadata_parts[0].text.toString());
            // TODO authorVerified if possible
        } else return error("Channel header type not supported");
        // About info (TODO: Add config option to disable this so this doesn't need to do 2 requests)
        if (about.is(YTNodes.AboutChannel)) {
            extras.totalViews = formatNum(about.metadata.view_count);
            extras.joined = formatDate(about.metadata.joined_date.toString().replace("Joined ",""));
            extras.description = about.metadata.description;
            extras.descriptionHtml = formatHtml(extras.description) // TODO: See if there's a proper way to get HTML
        } else {
            extras.totalViews = formatNum(about.view_count.toString());
            extras.joined = formatDate(about.joined_date.toString().replace("Joined ","")); // TODO: Check if this is the same kind of string vused in the AboutChannel node
            extras.description = about.description.toString();
            extras.descriptionHtml = about.description.toHTML();
        }
        // Auto generated check
        // https://support.google.com/youtube/answer/2579942
        // https://github.com/iv-org/invidious/blob/b13f77b5afe72b5258d2a9484833a7b7e0fd0944/src/invidious/channels/channels.cr#L180-L185
        if (channel.metadata.title.endsWith(" - Topic") ||
            ["Popular on YouTube", "Music", "Sports", "Gaming"].includes(channel.metadata.title)) {
            extras.autoGenerated = true
        }

        // videos
        const author: AuthorStub = {
            name: channel.metadata.title,
            id: channel.metadata.external_id,
            url: channel.metadata.url,
            is_verified: extras.authorVerified
        }
        const videos = await channel.getVideos();
        for (let video of videos.videos) {
            extras.latestVideos.push(channelVideo(video, author));
        }

        // channels
        for (let related of channel.channels) {
            extras.channels.push(channelRelated(related));
        }

        return obj({
            author: author.name,
            authorId: author.id,
            authorUrl: author.name,
            authorBanners: extras.banners,
            authorThumbnails: channel.metadata.avatar,
            subCount: extras.subCount,
            totalViews: extras.totalViews,
            joined: extras.joined,
            autoGenerated: extras.autoGenerated,
            ageGated: false, // TODO (I don't believe this is implemented in YT.JS anyways but it'd be nice to have 100% parity)
            isFamilyFriendly: channel.metadata.is_family_safe,
            description: extras.description,
            descriptionHtml: extras.descriptionHtml,
            allowedRegions: channel.metadata.available_countries,
            tabs: channel.tabs, // TODO: Maybe remove Store if present?
            tags: channel.metadata.tags,
            authorVerified: author.is_verified,
            latestVideos: extras.latestVideos,
            relatedChannels: extras.channels
        });
    } catch (e) {
        return error(e.message);
    }
};
