// TODO: stronger typesetting
export interface ImageObject {
    url: string,
    width: number,
    height: number
}
export interface ThumbnailObject {
    quality: string,
    url: string,
    width: number,
    height: number
}
export interface VideoObject {
    type: "video",
    title: string,
    videoId: string,
    author: string,
    authorId: string,
    authorUrl: string,
    authorVerified: boolean,
    videoThumbnails: ThumbnailObject[],
    description: string,
    descriptionHtml: string,
    viewCount: number,
    viewCountText: string,
    lengthSeconds: number,
    published: number,
    publishedText: string,
    premiereTimestamp: number,
    liveNow: boolean,
    premium: boolean,
    isUpcoming: boolean
}
export interface ChannelObject {
    type: "channel",
    author: string,
    authorId: string,
    authorUrl: string,
    authorVerified: string,
    authorThumbnails: ThumbnailObject[],
    autoGenerated: boolean,
    subCount: number,
    videoCount: number,
    description: string,
    descriptionHtml: string
}